# below line is for err : 'rakefile not found'
language: generic 
sudo : required
services : 
  - docker

before_install : 
  - docker build -t pradyumnarutvik/react-test -f ./client/Dockerfile.dev ./client

scripts :
  - docker run -e CI=true pradyumnarutvik/react-test npm run test

after_success :
  - docker build -t pradyumnarutvik/multi-client ./client
  - docker build -t pradyumnarutvik/multi-nginx ./nginx
  - docker build -t pradyumnarutvik/multi-server ./server
  - docker build -t pradyumnarutvik/multi-worker ./worker
  # login into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take above images and push them to docker-hub
  - docker push pradyumnarutvik/multi-client
  - docker push pradyumnarutvik/multi-nginx
  - docker push pradyumnarutvik/multi-server
  - docker push pradyumnarutvik/multi-worker